# -*- coding: utf-8 -*-
"""Copia de Caso Practico Python - Tuberculosis RP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZOSNAK5AkwEOkfE9lqWYBflfuvCWYAi

# Análisis de Tuberculosis

**Planteamiento**

Usted trabaja para la Organización Mundial de la Salud como analista de información. El consejo directivo se reunirá para revisar los datos más recientes de casos de tuberculosis.

Los datos han llegado con la información más reciente y necesita prepararlos para mostrar la información a los líderes de la organización.

El objetivo de la junta es entender la situación actual de tuberculosis, y las tendencias por región e identificar países que han sido casos de éxito y aquellos que necesiten mayor apoyo con la gestión de la enfermedad.

Tenga en mente las metas de la ONU para terminar con la tuberculosis para 2025:

*  Reducción en la tasa de incidencia del 50% 2015 vs 2025.
*  Reducción en 75% el número de muertes 2015 vs 2025

1. ¿Que es la tuberculosis?

La tuberculosis es una de las enfermedades infecciosas más antiguas y conocidas de la humanidad. De acuerdo a la Organización Mundial de la Salud (OMS), un tercio de la población mundial está infectada por el Bacilo de la Tuberculosis (Mycobacterium tuberculosis o “Bacilo de Koch”), con el riesgo de desarrollar la enfermedad en algún momento de su vida. Se considera un desafío vigente para la salud pública de países como el nuestro ya que una persona enferma por TB sin tratamiento puede infectar de 15 a 20 personas por año.
La TB puede afectar cualquier órgano del cuerpo humano; sin embargo la forma más frecuente es la que se manifiesta en los pulmones (tuberculosis pulmonar) en un 85% de los casos. Otros lugares frecuentes donde se puede manifestar son: ganglios linfáticos, riñones, cerebro (sistema nervioso central) y huesos.
 La presencia y evolución de la enfermedad, así como el pronóstico pueden empeorar si la persona padece diabetes mellitus, VIH-SIDA, alcoholismo, desnutrición, cáncer o situaciones en las que la persona tenga baja inmunidad. Se puede aumentar el contagio si la persona convive con personas enfermas de TB sobre todo en lugares con poca ventilación.
Existen grupos de personas que pueden tener más riesgo de enfermar debido a sus condicionantes sociales, por ejemplo, niños, ancianos, privados de su libertad, personal de salud, migrantes, indígenas e indigentes.

2. ¿Cómo se transmite la TB?

La transmisión de la tuberculosis pulmonar (TBP) es por vía aérea cuando un enfermo expulsa micro gotas de saliva con bacilos de la tuberculosis (aerosoles) al toser, hablar, cantar o estornudar cerca de otras personas sanas. Una medida para reducir el riesgo de contagio es que las personas se cubran la boca y la nariz al toser o estornudar.

3. ¿Cuáles son los síntomas de la TB?

Para el caso de la tuberculosis pulmonar la principal manifestación es la tos con flemas (expectoración) de más de 15 días. Se puede acompañar de fiebre por las tardes, pérdida de peso sin causa aparente, sudoraciones nocturnas, falta de apetito y sensación de cansancio principalmente, sin embargo cuando llega a agravarse también se puede notar dolor de pecho, dificultad para respirar, sangrado al toser y dolor de cabeza.

4. ¿Cómo se hace diagnóstico de la TB?

Principalmente por la sospecha de la enfermedad ante los signos y síntomas antes mencionados, y se confirma por el laboratorio  mediante La BACILOSCOPÍA que es el método de más fácil acceso el cual consiste en obtener una muestra de la flema del afectado (gargajo, pollo, esputo) al momento en que acude a consulta médica.

Se puede complementar utilizando radiografías de tórax para determinar la extensión del daño por la enfermedad. Sin embargo, el mejor estudio de laboratorio que confirma un caso nuevo es el Cultivo de Micobacterias.

Existen otros métodos de diagnóstico más especializados los cuales dependerán de su disponibilidad en los centros de salud del país.

El diagnóstico de la tuberculosis no tiene costo para el usuario que acude a los servicios de salud en las instituciones (Secretaria de Salud, IMSS, ISSSTE).


5. ¿Es posible prevenir la TB?

La vacunación por BCG se aplica de manera universal y gratuita a todos los recién nacidos (preferentemente antes de salud de la unidad de salud donde nació), con lo que se previene la aparición de formas graves de tuberculosis como la del sistema nervioso central o meníngea, que es de muy alta mortalidad.

Existen algunas medidas destinadas a disminuir, reducir y/o evitar la transmisión de la tuberculosis como por ejemplo la identificación oportuna de personas con tos y flemas de más de 15 días con realización inmediata de examen de la flema (baciloscopía), establecer el diagnóstico de manera rápida, inicio rápido y SUPERVISIÓN ESTRICTA de la toma del medicamento por parte del personal de salud, evitar tiempos de espera prolongados en las salas de los centros de salud y/o hospitales.

Es importante que se fomente la ventilación en los lugares donde se encuentren los afectados y optimizar la ventilación natural abriendo las ventanas y las personas se cubran la boca con un papel, pañuelo y/o servilleta al momento de toser o estornudar.

Es necesario que el personal de salud identifique síntomas respiratorios en quienes conviven con un afectado por esta enfermedad (estudio de contactos), dependiendo de la edad y si tienen antecedentes de haber sido vacunados, si los contactos de un enfermo de TB, son menores de 5 años o de cualquier edad que tengan alguna condición que disminuya las defensas del cuerpo y que no presentan síntomas de TB se les puede brindar tratamiento preventivo para evitar que desarrollen la enfermedad. Es importante mencionar que la vacuna previene las formas graves de TB, esto es la Meningitis por Tuberculosis.

6. ¿Existe tratamiento para la TB?

La tuberculosis es una enfermedad CURABLE. El tratamiento está disponible y es GRATUITO en todas las unidades del Sistema Nacional de Salud. En general tiene una duración de 6 meses el cual debe tomar el paciente sin interrumpirlo aunque en el transcurso de este tiempo se sienta completamente curado.

El éxito del tratamiento dependerá principalmente de la SUPERVISIÓN ESTRICTA de la toma del medicamento en la unidad de salud; así mismo dependerá de la comunicación, interacción y participación activa entre el personal de salud y el afectado por esta enfermedad.

Es importante que los afectados por TB cumplan todo el tiempo de su tratamiento y no lo abandonen, ya que la enfermedad puede reactivarse y convertirse en farmacorresistente, lo cual implica un nuevo tratamiento, mucho más prolongado, de 2 o más años y con fármacos que implican un inyectable por lo menos 10 meses aparte de los efectos adversos del resto de los medicamentos en esta situación de fármacorresistencia.  

**Preguntas a responder del analisis de datos**

7. ¿Cual es la mayor insidencia por edad?
8. ¿A que sexo afecta mas la tuberculosis?
9. ¿Cúal es la mayor insidencia por diagnostico?
"""

from google.colab import drive
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

drive.mount('/content/drive')

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

"""#Manipulación y Limpieza de datos

**Acerca de los datos**

Un conjunto de datos del Informe Global sobre Tuberculosis de la Organización Mundial de la Salud (OMS), junto con datos de poblaciones globales.
El conjunto utiliza los códigos originales de la OMS.

Los nombres de las columnas de la columna 5 a la 60 se forman combinando *new_* con:
*   El método de diagnóstico (*rel* = recaída, *sn* = esputo pulmonar negativo, *sp* = esputo pulmonar positivo, *ep* = extrapulmonar).

*   El género (*f* = femenino, *m* = masculino).


*   El grupo de edad (*014* = 0 a 14 años, *1524* = 15 a 24, *2534* = 25 a 34, *3544* = 35 a 44, *4554* = 45 a 54, *5564* = 55 a 64, *65* = 65 años o más).

Carga de Datos
"""

# Carga de datos

import pandas as pd
who = pd.read_csv("/content/drive/MyDrive/Recursos Colab/who.csv")

import pandas as pd
population = pd.read_csv("/content/drive/MyDrive/Recursos Colab/population.csv")

"""# Limpieza de Datos"""

# Manejo de valores faltantes
who.loc[who.country == "Namibia", "iso2"] = "NA"
who = who.fillna(0)

# Transformación de datos
who2 = who.melt(id_vars=["country", "year", "iso2", "iso3"], var_name="variable", value_name="cases")

# Asignar género
who2["gender"] = np.where(who2["variable"].str.contains("m"), "masculino", "femenino")

# Funciones para asignar grupos
def asignar_groupedad(valor):
    if "014" in valor: return "0-14"
    elif "1524" in valor: return "15-24"
    elif "2534" in valor: return "25-34"
    elif "3544" in valor: return "35-44"
    elif "4554" in valor: return "45-54"
    elif "5564" in valor: return "55-64"
    elif "65" in valor: return "65+"

def asignar_metodo(valor):
    if "rel" in valor: return "recaída"
    elif "sn" in valor: return "esputo pulmonar negativo"
    elif "sp" in valor: return "esputo pulmonar positivo"
    elif "ep" in valor: return "extrapulmonar"

who2["agegroup"] = who2["variable"].apply(asignar_groupedad)
who2["method"] = who2["variable"].apply(asignar_metodo)

# Combinar con datos de población
df = pd.merge(left=who2, right=population, how="inner", on=["country", "year"])

# Calcular tasas de incidencia
by_country_year = df.groupby(["country", "year"], as_index=False).agg(
    {"cases":"sum", "population":"max"}
)
by_country_year["incidencia"] = 100000 * by_country_year["cases"] / by_country_year["population"]

by_year = by_country_year.groupby("year", as_index=False).agg(
    {"cases":"sum", "population": "sum"}
)
by_year["incidencia"] = 100_000 * by_year["cases"] / by_year["population"]

# Guardar datos limpios
df.to_csv("tuberculosis_clean.csv", index=False)
by_country_year.to_csv("tuberculosis_by_country_year.csv", index=False)
by_year.to_csv("tuberculosis_by_year.csv", index=False)

who2.head()

"""#Análisis Exploratorio

# 1. Distribución por Género
"""

by_gender = df.groupby("gender", as_index=False)["cases"].sum()
by_gender["percent_of_total"] = 100 * by_gender["cases"] / by_gender["cases"].sum()

plt.figure(figsize=(8, 6))
sns.barplot(data=by_gender, x="gender", y="percent_of_total")
plt.title("Distribución de casos por género")
plt.xlabel("Género")
plt.ylabel("Porcentaje del total")
plt.show()

"""# 2. Distribución por Grupo de Edad"""

by_agegroup = df.groupby("agegroup", as_index=False)["cases"].sum()
by_agegroup["percent_of_total"] = 100 * by_agegroup["cases"] / by_agegroup["cases"].sum()

plt.figure(figsize=(10, 6))
sns.barplot(data=by_agegroup, x="agegroup", y="percent_of_total", order=["0-14", "15-24", "25-34", "35-44", "45-54", "55-64", "65+"])
plt.title("Distribución de casos por grupo de edad")
plt.xlabel("Grupo de edad")
plt.ylabel("Porcentaje del total")
plt.show()

"""# 3. Tasa de Incidencia de tuberculosisi (1995-2013)"""

plt.figure(figsize=(12, 6))
sns.lineplot(data=by_year, x="year", y="incidencia")
plt.title("Tasa de incidencia de tuberculosis (1995-2013)")
plt.xlabel("Año")
plt.ylabel("Casos por 100,000 habitantes")
plt.grid(True)
plt.show()

"""# 4. Países con Mayor Carga de Tuberculosis"""

top_countries = df.groupby("country", as_index=False)["cases"].sum().sort_values("cases", ascending=False).head(10)

plt.figure(figsize=(12, 6))
sns.barplot(data=top_countries, x="cases", y="country")
plt.title("Top 10 países con mayor número de casos (1995-2013)")
plt.xlabel("Número de casos")
plt.ylabel("País")
plt.show()

"""# 5. TASA DE INCIDENCIA GLOBAL POR AÑO"""

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Configuración de estilo para todos los gráficos
sns.set_style("whitegrid")
plt.rcParams['figure.dpi'] = 120
plt.rcParams['font.size'] = 10

# 1. Gráfico de Tasa de Incidencia Global por Año (Matplotlib/Seaborn)
plt.figure(figsize=(12, 6))
ax = sns.lineplot(data=by_year, x='year', y='incidencia',
                  marker='o', linewidth=2.5, color='#1f77b4')

# Personalización
plt.title('Evolución de la Tasa de Incidencia Global de Tuberculosis (1995-2013)\nCasos por 100,000 habitantes',
          pad=20, fontsize=12, fontweight='bold')
plt.xlabel('Año', labelpad=10)
plt.ylabel('Tasa de Incidencia', labelpad=10)
plt.xticks(by_year['year'][::2])  # Mostrar años alternados para mejor legibilidad

# Destacar puntos clave
max_incidencia = by_year.loc[by_year['incidencia'].idxmax()]
ax.annotate(f'Pico: {max_incidencia["year"]}\n({max_incidencia["incidencia"]:.1f} casos)',
            xy=(max_incidencia['year'], max_incidencia['incidencia']),
            xytext=(10, 30), textcoords='offset points',
            arrowprops=dict(arrowstyle="->", color='red'),
            bbox=dict(boxstyle="round", fc="w"))

# Guardar gráfico
plt.tight_layout()
plt.savefig('tasa_incidencia_global.png', bbox_inches='tight', dpi=300)
plt.show()

from google.colab import files
files.download('tuberculosis_clean.csv')

"""# 6. Gráfico de Casos por Método de Diagnóstico (Plotly - Interactivo)"""

# 6. Gráfico de Casos por Método de Diagnóstico (Plotly - Interactivo)
# Preprocesamiento para ordenar los métodos
by_method_sorted = by_method.sort_values('percent_of_total', ascending=False)

fig = px.bar(by_method_sorted,
             x='method',
             y='percent_of_total',
             color='method',
             color_discrete_sequence=px.colors.qualitative.Pastel,
             text='percent_of_total',
             title='<b>Distribución de Casos por Método de Diagnóstico</b><br><sup>Porcentaje del total de casos</sup>',
             labels={'percent_of_total': 'Porcentaje (%)', 'method': 'Método de Diagnóstico'})

# Personalización
fig.update_traces(texttemplate='%{text:.1f}%', textposition='outside')
fig.update_layout(
    hovermode='x',
    showlegend=False,
    title_x=0.5,
    xaxis_tickangle=-45,
    yaxis_range=[0, by_method_sorted['percent_of_total'].max() + 10],
    plot_bgcolor='rgba(0,0,0,0)'
)

# Añadir anotación con insights
fig.add_annotation(
    x=0.5, y=-0.3,
    xref='paper', yref='paper',
    text="El diagnóstico por esputo pulmonar positivo representa más de la mitad de los casos identificados",
    showarrow=False,
    font=dict(size=10, color='grey')
)
# Guardar gráfico interactivo
fig.write_html('casos_por_metodo.html')
fig.show()

# Versión estática para PDF
plt.figure(figsize=(10, 6))
sns.barplot(data=by_method_sorted, x='method', y='percent_of_total',
            palette='pastel', edgecolor='black')
plt.title('Distribución de Casos por Método de Diagnóstico', pad=15)
plt.xlabel('Método de Diagnóstico')
plt.ylabel('Porcentaje del Total (%)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('casos_por_metodo.png', dpi=300)
plt.show()